/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ChefAddFoodRouteImport } from './routes/chef.add-food'
import { Route as ChefDashboardRouteImport } from './routes/chef.dashboard'
import { Route as ChefMenuRouteImport } from './routes/chef.menu'
import { Route as ChefOrdersRouteImport } from './routes/chef.orders'
import { Route as ChefRegisterRouteImport } from './routes/chef.register'
import { Route as DishDishIdRouteImport } from './routes/dish.$dishId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefAddFoodRoute = ChefAddFoodRouteImport.update({
  id: '/chef/add-food',
  path: '/chef/add-food',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefDashboardRoute = ChefDashboardRouteImport.update({
  id: '/chef/dashboard',
  path: '/chef/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefMenuRoute = ChefMenuRouteImport.update({
  id: '/chef/menu',
  path: '/chef/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefOrdersRoute = ChefOrdersRouteImport.update({
  id: '/chef/orders',
  path: '/chef/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRegisterRoute = ChefRegisterRouteImport.update({
  id: '/chef/register',
  path: '/chef/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DishDishIdRoute = DishDishIdRouteImport.update({
  id: '/dish/$dishId',
  path: '/dish/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/chef/add-food': typeof ChefAddFoodRoute
  '/chef/dashboard': typeof ChefDashboardRoute
  '/chef/menu': typeof ChefMenuRoute
  '/chef/orders': typeof ChefOrdersRoute
  '/chef/register': typeof ChefRegisterRoute
  '/dish/$dishId': typeof DishDishIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/chef/add-food': typeof ChefAddFoodRoute
  '/chef/dashboard': typeof ChefDashboardRoute
  '/chef/menu': typeof ChefMenuRoute
  '/chef/orders': typeof ChefOrdersRoute
  '/chef/register': typeof ChefRegisterRoute
  '/dish/$dishId': typeof DishDishIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/chef/add-food': typeof ChefAddFoodRoute
  '/chef/dashboard': typeof ChefDashboardRoute
  '/chef/menu': typeof ChefMenuRoute
  '/chef/orders': typeof ChefOrdersRoute
  '/chef/register': typeof ChefRegisterRoute
  '/dish/$dishId': typeof DishDishIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/profile'
    | '/register'
    | '/chef/add-food'
    | '/chef/dashboard'
    | '/chef/menu'
    | '/chef/orders'
    | '/chef/register'
    | '/dish/$dishId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/profile'
    | '/register'
    | '/chef/add-food'
    | '/chef/dashboard'
    | '/chef/menu'
    | '/chef/orders'
    | '/chef/register'
    | '/dish/$dishId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/profile'
    | '/register'
    | '/chef/add-food'
    | '/chef/dashboard'
    | '/chef/menu'
    | '/chef/orders'
    | '/chef/register'
    | '/dish/$dishId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ExploreRoute: typeof ExploreRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ChefAddFoodRoute: typeof ChefAddFoodRoute
  ChefDashboardRoute: typeof ChefDashboardRoute
  ChefMenuRoute: typeof ChefMenuRoute
  ChefOrdersRoute: typeof ChefOrdersRoute
  ChefRegisterRoute: typeof ChefRegisterRoute
  DishDishIdRoute: typeof DishDishIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/add-food': {
      id: '/chef/add-food'
      path: '/chef/add-food'
      fullPath: '/chef/add-food'
      preLoaderRoute: typeof ChefAddFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/dashboard': {
      id: '/chef/dashboard'
      path: '/chef/dashboard'
      fullPath: '/chef/dashboard'
      preLoaderRoute: typeof ChefDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/menu': {
      id: '/chef/menu'
      path: '/chef/menu'
      fullPath: '/chef/menu'
      preLoaderRoute: typeof ChefMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/orders': {
      id: '/chef/orders'
      path: '/chef/orders'
      fullPath: '/chef/orders'
      preLoaderRoute: typeof ChefOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/register': {
      id: '/chef/register'
      path: '/chef/register'
      fullPath: '/chef/register'
      preLoaderRoute: typeof ChefRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish/$dishId': {
      id: '/dish/$dishId'
      path: '/dish/$dishId'
      fullPath: '/dish/$dishId'
      preLoaderRoute: typeof DishDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ExploreRoute: ExploreRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ChefAddFoodRoute: ChefAddFoodRoute,
  ChefDashboardRoute: ChefDashboardRoute,
  ChefMenuRoute: ChefMenuRoute,
  ChefOrdersRoute: ChefOrdersRoute,
  ChefRegisterRoute: ChefRegisterRoute,
  DishDishIdRoute: DishDishIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
